# Config file for automatic testing at travis-ci.org
cache: pip
sudo: false

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

env:
  - DJANGO="Django>=1.7,<1.8"
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="Django>=1.10,<1.11"
  - DJANGO="Django>=1.11,<2"
  - DJANGO="https://github.com/django/django/tarball/master"


matrix:
  exclude:
    - python: "3.5"
      env: DJANGO="Django>=1.7,<1.8"
  allow_failures:
    - env: DJANGO="https://github.com/django/django/tarball/master"


before_install:
    - pip install codecov

install:
    - pip install $DJANGO && pip install -r requirements-test.txt

script:
    - coverage run --source=dynamic_preferences pytest

after_success:
    - codecov
